// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: compiler.jflex

// User code
import java.util.*;
import java.io.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class vc {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\3\3\22\0\1\1\1\4\4\0"+
    "\1\5\1\0\1\6\1\7\1\10\1\11\1\12\1\11"+
    "\1\12\1\13\12\14\1\0\1\12\1\4\1\15\1\4"+
    "\2\0\32\16\1\17\1\0\1\20\3\0\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\16\1\27\1\30\1\16"+
    "\1\31\1\32\1\33\1\34\1\35\2\16\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\3\16\1\12\1\44\1\12"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\1\1\5\2\4"+
    "\1\6\1\7\12\10\1\1\1\11\1\12\1\13\1\0"+
    "\6\10\1\14\5\10\2\0\1\15\5\10\1\16\1\17"+
    "\4\10\1\12\3\10\1\20\4\10\1\21\1\10\1\13"+
    "\1\10\1\22\2\10\1\23\1\24\1\10\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\45\0\45\0\157\0\224\0\45"+
    "\0\45\0\271\0\336\0\157\0\u0103\0\u0128\0\u014d\0\u0172"+
    "\0\u0197\0\u01bc\0\u01e1\0\u0206\0\u022b\0\u0250\0\u0275\0\u029a"+
    "\0\u02bf\0\45\0\u02e4\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d"+
    "\0\u03c2\0\u0103\0\u03e7\0\u040c\0\u0431\0\u0456\0\u047b\0\u029a"+
    "\0\u04a0\0\45\0\u04c5\0\u04ea\0\u050f\0\u0534\0\u0559\0\u0103"+
    "\0\u0103\0\u057e\0\u05a3\0\u05c8\0\u05ed\0\45\0\u0612\0\u0637"+
    "\0\u065c\0\u0103\0\u0681\0\u06a6\0\u06cb\0\u06f0\0\u0103\0\u0715"+
    "\0\u073a\0\u075f\0\u0103\0\u0784\0\u07a9\0\45\0\u0103\0\u07ce"+
    "\0\u0103";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\2\10\2\11"+
    "\1\10\1\12\1\13\1\14\1\15\2\2\1\15\1\16"+
    "\1\17\1\15\1\20\1\21\1\15\1\22\2\15\1\23"+
    "\2\15\1\24\3\15\1\25\1\26\1\27\46\0\1\3"+
    "\60\0\1\11\34\0\1\11\47\0\1\30\2\0\1\31"+
    "\45\0\1\13\36\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\23\15\7\0\1\32\5\0\1\15\1\0"+
    "\1\15\1\33\1\0\14\15\1\34\1\35\5\15\7\0"+
    "\1\32\5\0\1\15\1\0\1\15\1\33\1\0\14\15"+
    "\1\36\6\15\7\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\11\15\1\37\11\15\7\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\11\15\1\40\2\15"+
    "\1\41\6\15\7\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\5\15\1\42\5\15\1\43\7\15\7\0"+
    "\1\32\5\0\1\15\1\0\1\15\1\33\1\0\1\44"+
    "\22\15\7\0\1\32\5\0\1\15\1\0\1\15\1\33"+
    "\1\0\4\15\1\45\16\15\7\0\1\32\5\0\1\15"+
    "\1\0\1\15\1\33\1\0\14\15\1\46\6\15\7\0"+
    "\1\32\5\0\1\15\1\0\1\15\1\33\1\0\6\15"+
    "\1\47\14\15\45\0\1\11\10\50\1\51\34\50\2\31"+
    "\2\0\41\31\14\0\1\33\3\0\1\52\32\0\1\32"+
    "\5\0\1\15\1\0\1\15\1\33\1\0\14\15\1\53"+
    "\6\15\7\0\1\32\5\0\1\15\1\0\1\15\1\33"+
    "\1\0\4\15\1\54\16\15\7\0\1\32\5\0\1\15"+
    "\1\0\1\15\1\33\1\0\13\15\1\55\7\15\7\0"+
    "\1\32\5\0\1\15\1\0\1\15\1\33\1\0\16\15"+
    "\1\56\4\15\7\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\14\15\1\57\6\15\7\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\15\15\1\60\5\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\17\15\1\61\3\15\7\0\1\32\5\0\1\15\1\0"+
    "\1\15\1\33\1\0\7\15\1\62\13\15\7\0\1\32"+
    "\5\0\1\15\1\0\1\15\1\33\1\0\17\15\1\63"+
    "\3\15\7\0\1\32\5\0\1\15\1\0\1\15\1\33"+
    "\1\0\7\15\1\64\13\15\7\0\1\32\5\0\1\15"+
    "\1\0\1\15\1\33\1\0\7\15\1\65\13\15\1\0"+
    "\10\50\1\51\2\50\1\66\31\50\6\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\11\15\1\67\11\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\1\70\22\15\7\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\17\15\1\71\3\15\7\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\4\15\1\72\16\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\1\43\22\15\7\0\1\32\5\0\1\15\1\0\1\15"+
    "\1\33\1\0\13\15\1\73\7\15\7\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\20\15\1\74\2\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\3\15\1\61\17\15\7\0\1\32\5\0\1\15\1\0"+
    "\1\15\1\33\1\0\11\15\1\75\11\15\7\0\1\32"+
    "\5\0\1\15\1\0\1\15\1\33\1\0\4\15\1\76"+
    "\16\15\7\0\1\32\5\0\1\15\1\0\1\15\1\33"+
    "\1\0\10\15\1\77\12\15\7\0\1\32\5\0\1\15"+
    "\1\0\1\15\1\33\1\0\7\15\1\100\13\15\7\0"+
    "\1\101\5\0\1\15\1\0\1\15\1\33\1\0\23\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\15\15\1\102\5\15\7\0\1\32\5\0\1\15\1\0"+
    "\1\15\1\33\1\0\4\15\1\103\16\15\7\0\1\32"+
    "\5\0\1\15\1\0\1\15\1\33\1\0\1\104\22\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\13\15\1\105\7\15\10\0\1\106\43\0\1\32\5\0"+
    "\1\15\1\0\1\15\1\33\1\0\13\15\1\107\7\15"+
    "\7\0\1\32\5\0\1\15\1\0\1\15\1\33\1\0"+
    "\13\15\1\61\7\15\7\0\1\32\5\0\1\15\1\0"+
    "\1\15\1\33\1\0\20\15\1\110\2\15\7\0\1\32"+
    "\5\0\1\15\1\0\1\15\1\33\1\0\4\15\1\111"+
    "\16\15\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2035];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\2\1\2\11\20\1\1\11"+
    "\1\0\14\1\2\0\1\11\13\1\1\11\17\1\1\11"+
    "\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[73];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
    public static File file = new File("output.txt");

    public static void WriteToFile(String content) {
        try {
            FileWriter myFile = new FileWriter(file, true);
            myFile.write(content + "\n");
            myFile.close();
        } catch (IOException e) {
            WriteToFile("An error occurred.");
            e.printStackTrace();
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  vc(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { WriteToFile(yytext() + "\t Unknown");
            }
            // fall through
          case 22: break;
          case 2:
            { 
            }
            // fall through
          case 23: break;
          case 3:
            { System.out.print(yytext());
            }
            // fall through
          case 24: break;
          case 4:
            { WriteToFile(yytext() + "\t Operator");
            }
            // fall through
          case 25: break;
          case 5:
            { WriteToFile(yytext() + "\t Separators");
            }
            // fall through
          case 26: break;
          case 6:
            { WriteToFile(yytext() + "\t Number");
            }
            // fall through
          case 27: break;
          case 7:
            { WriteToFile(yytext() + "\t Assign");
            }
            // fall through
          case 28: break;
          case 8:
            { WriteToFile(yytext() + "\t Variable");
            }
            // fall through
          case 29: break;
          case 9:
            { System.out.println("Unclosed comment");
            }
            // fall through
          case 30: break;
          case 10:
            { /* Do Nothing */
            }
            // fall through
          case 31: break;
          case 11:
            { WriteToFile(yytext() + "\t Function");
            }
            // fall through
          case 32: break;
          case 12:
            { WriteToFile(yytext() + "\t If");
            }
            // fall through
          case 33: break;
          case 13:
            { WriteToFile(yytext() + "\t Array");
            }
            // fall through
          case 34: break;
          case 14:
            { WriteToFile(yytext() + "\t For");
            }
            // fall through
          case 35: break;
          case 15:
            { WriteToFile(yytext() + "\t Type");
            }
            // fall through
          case 36: break;
          case 16:
            { WriteToFile(yytext() + "\t Else");
            }
            // fall through
          case 37: break;
          case 17:
            { WriteToFile(yytext() + "\t Break");
            }
            // fall through
          case 38: break;
          case 18:
            { WriteToFile(yytext() + "\t While");
            }
            // fall through
          case 39: break;
          case 19:
            { WriteToFile(yytext() + "\t Main function");
            }
            // fall through
          case 40: break;
          case 20:
            { WriteToFile(yytext() + "\t Return");
            }
            // fall through
          case 41: break;
          case 21:
            { WriteToFile(yytext() + "\t Continue");
            }
            // fall through
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java vc [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        vc scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new vc(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
